version: "3.1"

services:
  db:
    image: postgres:9.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: demo
      POSTGRES_DB: l2
    ports:
      - 5432:5432
